# Generated by Django 3.2.10 on 2022-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Donate',
            field=models.IntegerField(default=0),
        ),
    ]
