# Generated by Django 3.2.10 on 2022-01-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='formviewtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('work', models.CharField(max_length=100)),
                ('ROW', models.CharField(max_length=500)),
            ],
        ),
    ]
