# Generated by Django 3.2.10 on 2022-01-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_formviewtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='formviewtable',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
